CIRCUITPY_WIFI_SSID = "YOUR_WIFI_SSID"
CIRCUITPY_WIFI_PASSWORD = "YOUR_WIFI_PASSWORD"
CIRCUITPY_WEB_API_PASSWORD = "password"
CIRCUITPY_WEB_API_PORT = 80
CIRCUITPY_WEB_INSTANCE_NAME = "IKEA Fornuftig - ItsyBitsy ESP32"
CIRCUITPY_AIO_USERNAME = "YOUR_ADAFRUIT_IO_USERNAME"
CIRCUITPY_AIO_KEY = "YOUR_ADAFRUIT_IO_KEY"
FAN_SPEED_FEEDNAME = "fan-speed3"
AIR_QUALITY_FEEDNAME = "ecda3bbc63d4-seeed-xiao-esp32c3-sen5x-ppm-2-dot-5"
NOISE_LEVEL_1_MAX_FAN_FREQUENCY = 140
NOISE_LEVEL_2_MAX_FAN_FREQUENCY = 220
NOISE_LEVEL_3_MAX_FAN_FREQUENCY = 300